### ISSUE TITLE
Website design

### ISSUE THREAD

**Issue by heron2014** [node-girls/start-here#7]
I made this design quite a while ago, thought I will share it :) (That was my starting point)

@NataliaLKB If you have some other ideas please do share , I would love to see it or all of us can help. 

First one: 

![mokupnodeg](https://cloud.githubusercontent.com/assets/8476884/12292652/6e382818-b9e6-11e5-9be1-37394b32daa2.jpg)

Second one : 

![mokupnodeg1](https://cloud.githubusercontent.com/assets/8476884/12292712/f2e3f132-b9e6-11e5-9842-0f32a6db3ad3.jpg)

**Comment by NataliaLKB** [comment]
@heron2014 I like it, but for the landing page for the 19th I think just getting something simple out without any links is the most important. It will be solely a landing page, unless you have the time to put something more together by then? 

This design would be a nice starting point for the whole website. Only thing I will mention about the design, I think that graphs on the computer screen maybe a tad misleading, but that is a minor change. Otherwise the layout is really nice. Did you have a design for how it will look on mobile too?

I wonder if also having _Why_ or _Why Node_ would be good links maybe instead of overview?

**Comment by heron2014** [comment]
Yes sure, totally agree, we can change the links or even eliminate them. If you like the design (computer screen can be changed :) ) , I can make mobile version as well. But is really up to you, if you want to do something else, don't worry about this one :smile:

**Comment by NataliaLKB** [comment]
Great! We can talk more about this on the Hackday!

**Comment by heron2014** [comment]
Lovely :)

**Comment by heron2014** [comment]
![nodegirlslogo](https://cloud.githubusercontent.com/assets/8476884/12457325/c10b2a1c-bf9b-11e5-8ee0-2bc3d370ad7d.png)

![bgnodegirls](https://cloud.githubusercontent.com/assets/8476884/12457337/cf9009cc-bf9b-11e5-9fe6-136a267aa948.jpg)

@NataliaLKB I can email you svg  - typography for node girls , because github doesn’t support svg to upload here

**Comment by NataliaLKB** [comment]
@heron2014 Thanks so much! I sent you message with my email :smile:

**Comment by NataliaLKB** [comment]
Closing in favour of: https://github.com/node-girls/hackday/issues/9
